### ISSUE TITLE
会导致左边收起于展开按钮的点击事件

### ISSUE THREAD

**Issue by lovewmf** [HerbertHe/docsify-progress#1]

**Comment by HerbertHe** [comment]
能详细描述吗，如果能截图的话更好

**Comment by Joaxin** [comment]
This plugin will cause the click event of the left sidebar show/hide button muted. See the screenshots: 
[image.png](https://postimg.cc/1fpNnPwB)

**Comment by Joaxin** [comment]
This plugin will cause the click event of the left sidebar show/hide button muted. See the screenshots:
![](https://i.postimg.cc/jd161Sjp/image.png)
Will also cause the docsify-count plugin dead.
![](https://i.postimg.cc/65z668ZP/image.png)
---
该插件会导致侧边栏目录折叠按钮失效，同时导致docsify-count插件失效。

**Comment by HerbertHe** [comment]
我来找一下问题

**Comment by HerbertHe** [comment]
我做了修复，并且看起来已经是解决了，那个折叠的问题。看起来是因为 docsify 更新导致的，我直接重新为那个 button 添加了事件，已经修复了。docsify-count 这个插件也有一些相同的问题，把变量注册到了全局环境上造成了冲突（这个插件已经修复了），具体的冲突请联系那个开发者，我也只能PR。

**Comment by HerbertHe** [comment]
@lovewmf @Joaxin 我先关了这个issue, 如果还是有问题的话重开，最新的版本号为 `v1.0.2`，jsdelivr 的更新可能需要等一会才行

**Comment by HerbertHe** [comment]
`v.1.0.3` 修复了 docsify 事件监听导致的问题, 最新版我在手机调试和PC都试了，看起来没问题了
