### ISSUE TITLE
引入插件后移动端适配出现问题

### ISSUE THREAD

**Issue by sxin0** [HerbertHe/docsify-progress#2]
> 截图所示，侧边栏按钮失效
![image](https://user-images.githubusercontent.com/29392026/128447103-f3845200-6198-4eca-9ffb-865346c462bd.png)

**Comment by HerbertHe** [comment]
> > 截图所示，侧边栏按钮失效
> > ![image](https://user-images.githubusercontent.com/29392026/128447103-f3845200-6198-4eca-9ffb-865346c462bd.png)

最新版本已经解决了

**Comment by HerbertHe** [comment]
`1.0.3`
