### ISSUE TITLE
color元素渲染不出来导致进度条透明

### ISSUE THREAD

**Issue by vvmdx** [HerbertHe/docsify-progress#4]
在和其他插件混用时（其实还不是很确定是不是这个原因...因为当其他插件也有color键时也会造成丢失），color的值会丢失（赋值后依然渲染不到前端），导致前端的进度条虽然存在，但是是透明的

**Comment by HerbertHe** [comment]
@vvmdx 其实docsify官方默认加载的时候也是有进度条的，不知道你是不是以为的是那条线。。。这个插件的进度条是重新绘制的

**Comment by vvmdx** [comment]
> @vvmdx 其实docsify官方默认加载的时候也是有进度条的，不知道你是不是以为的是那条线。。。这个插件的进度条是重新绘制的

不是默认加载的那条线，因为我自己有调height值和颜色，所以前端定位看得出来是哪个，https://github.com/vvmdx/myDiary/blob/main/docs/index.html这是我的配置文件，http://vvmdx.cool 这是我的效果，一开始我查了有人说进度条和字数统计不兼容，但是我单独引入进度条和字数统计时是没问题的，后来不知道多了哪个插件就出问题了

**Comment by HerbertHe** [comment]
@vvmdx 字数统计那个插件也是我贡献的，应该不存在兼容问题，我看一下你的配置文件。

**Comment by HerbertHe** [comment]
我还真的没发现有啥兼容问题。。。可能是哪个插件生命周期有问题。。

**Comment by vvmdx** [comment]
@HerbertHe 我也没明白...我用chrome的f12查看的时候，发现进度条的前端样式是这样的
```
element.style {
    background-color: var(--theme-color, #FFA500);
    width: 0%;
    border-radius: 2px;
    height: 5px;
    transition: width 0.3s ease 0s;
}
```
按理来说width的值应该在0%~100%之间，但是我在滚动时，width的值会远大于100%，比如25000%之类的（造成了进度条要么没有，要么占满整条的结果）
而且更奇怪的一个地方是，当我开着F12控制台查看时，是能看到进度条的，然后关掉控制台就又看不到了，十分离谱。。

**Comment by HerbertHe** [comment]
呃，我感觉可能是Chrome的bug。。。我就没遇到过这种情况，代码逻辑也没错误啊。。

**Comment by vvmdx** [comment]
那就先不管了。。没太明白，总之感谢解答！

**Comment by HerbertHe** [comment]
你可以试一下Microsoft Edge
