### ISSUE TITLE
Adding Progress plugin makes Full Text Search do not work

### ISSUE THREAD

**Issue by LeetaH666** [HerbertHe/docsify-progress#5]
After adding Progress in my site, the Search plugin can not work until I remove the Progress.

**Comment by HerbertHe** [comment]
cloud you please provide version and minimum repo for debug?

**Comment by LeetaH666** [comment]
window.$docsify = {
          name: '',
          coverpage: true,
          loadNavbar: true,
          loadSidebar: true,
          subMaxLevel: 3,

          // Progress
          progress: {
            position: "top",
            color: "var(--theme-color, #42b983)",
            height: "3px",
          },

          // Full Text Search
          search: {
            maxAge: 86400000,
            paths: 'auto',
            placeholder: 'Type to search',
            noData: 'No Results!',
            depth: 6,
            hideOtherSidebarContent: false, 
          },
        }

    
    <script src="//cdn.jsdelivr.net/npm/docsify/lib/plugins/search.min.js"></script>

    
    <script src="https://cdn.jsdelivr.net/npm/docsify-progress@latest/dist/progress.min.js"></script>

Progress works well but Search shows nothing, even without 'No Results!'.

**Comment by LeetaH666** [comment]
I'm new to this, so I don't know what repo should I give. If you need any further information, just contact me.

**Comment by HerbertHe** [comment]
Maybe could you change the order for the plugin assets, and try again?

**Comment by LeetaH666** [comment]
Well, now the Search works but the Progress shows nothing 🤣 
BTW, why does the order matter?

**Comment by HerbertHe** [comment]
Maybe some conflicts happened? emmmm... I have forgiven docsify for a long time due to the slow first-screen render...

**Comment by HerbertHe** [comment]
The order of docsify plugins is very important, because it would cause effects when added plugins for docsify

**Comment by LeetaH666** [comment]
I see. Thank you for being so patient!

So is there any more excellent framework for markdown users? I just want to take notes and show them online. I think docsify is convenient for using just markdown instead of exporting files to html. Maybe using less plugins results in faster rendering?

**Comment by HerbertHe** [comment]
Now, I am contributing for Vditor(a markdown editor). Here are too many markdown docs tools, like VuePress, VitePress, dumi, Hugo, hexo...

**Comment by LeetaH666** [comment]
Wow, I'll check these out. Again thank U!
