### ISSUE TITLE
滑动直接就是100%了, 没有动态的效果

### ISSUE THREAD

**Issue by transon-top** [HerbertHe/docsify-progress#6]
如题.

我是基于https://jhildenbiddle.github.io/docsify-themeable/#/这个做的,  是不是有影响

**Comment by HerbertHe** [comment]
有最小复现仓库吗

**Comment by transon-top** [comment]
https://codesandbox.io/s/demo-docsify-themeable-forked-6j3oxk?file=/index.html

**Comment by transon-top** [comment]
拖动一下直接100%
我自己的站点也是这样的现象

**Comment by HerbertHe** [comment]
emmm你把这个插件放在最后面试试，docsify插件会相互影响的问题蛮严重的。。（唉，我都放弃docsify很久了）
