### ISSUE TITLE
与全局搜索插件和侧边栏标题的折叠冲突

### ISSUE THREAD

**Issue by WhyLIM** [HerbertHe/docsify-progress#7]
如题，

引入 js 后不能使用搜索，也不能折叠侧边栏 # H1 标题。

**Comment by HerbertHe** [comment]
请给一张截图和最小复现demo

**Comment by WhyLIM** [comment]
用简单的页面测试后发现，搜索的冲突应该是和其他插件共同引起的。。但是折叠的问题与其他插件没有关系。

比如这个示例中 https://cbd.limina.top/help/index.html#/Use 

`# H1 How to use` 展开时再次点击不会折叠，并且点击一级标题以外的标题（如二级标题 How to Search），相应标题也不会应用样式（本来应该会加粗并显示主题色）。

**Comment by HerbertHe** [comment]
> 用简单的页面测试后发现，搜索的冲突应该是和其他插件共同引起的。。但是折叠的问题与其他插件没有关系。
> 
> 比如这个示例中 https://cbd.limina.top/help/index.html#/Use
> 
> `# H1 How to use` 展开时再次点击不会折叠，并且点击一级标题以外的标题（如二级标题 How to Search），相应标题也不会应用样式（本来应该会加粗并显示主题色）。

我觉得很可能是因为插件顺序的原因吧，docsify插件设计是有缺陷的，并没有太多计划跟进docsify的。我个人是比较建议迁移到vitepress、dumi、vuepress等的。

**Comment by WhyLIM** [comment]
我试试别的，谢谢您
